# Generated by Django 4.1.4 on 2022-12-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=150, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('is_only_reference', models.BooleanField(default=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
