# Generated by Django 4.1.4 on 2022-12-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
    ]
