# Generated by Django 4.1.4 on 2022-12-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_appuser_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='loans.appuser', unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='loans.book', unique=True),
        ),
    ]
